### ISSUE TITLE
basic restoration prompt B in paper

### ISSUE THREAD

**Issue by Note-Liu** [longzilicart/pip_universal#2]
How to understand B and how to obtain B? What is the relationship between the shape of B(c×h×w) and the shape of Z？The section "Basic restoration prompt" does not provide  a clear introduction.

**Comment by longzilicart** [comment]
Hi, thank you for your attention. The details are provided in the supplementary material. In brief, we align Z with B, treating B's shape as an independent hyperparameter. In general, increasing 'c' enhances the capability of prompt at the expense of higher computational cost. Similarly, 'h' and 'w' are also trade-off parameters. We set h,w = H/2, W/2 and found it works well.

**Comment by Note-Liu** [comment]
> Hi, thank you for your attention. The details are provided in the supplementary material. In brief, we align Z with B, treating B's shape as an independent hyperparameter. In general, increasing 'c' enhances the capability of prompt at the expense of higher computational cost. Similarly, 'h' and 'w' are also trade-off parameters. We set h,w = H/2, W/2 and found it works well.

Thanks for your reply !

**Comment by Note-Liu** [comment]
Hi, I have another question to ask.
Is the shapes of U and Z the same?
Is the elements in each row of attention map A calculated by a certain channel in Z for each channel of U?
Thx!

**Comment by Note-Liu** [comment]
> Hi, thank you for your attention. The details are provided in the supplementary material. In brief, we align Z with B, treating B's shape as an independent hyperparameter. In general, increasing 'c' enhances the capability of prompt at the expense of higher computational cost. Similarly, 'h' and 'w' are also trade-off parameters. We set h,w = H/2, W/2 and found it works well.

Hi, I have another question to ask.
Is the shapes of U and Z the same?
Is the elements in each row of attention map A calculated by a certain channel in Z for each channel of U?
Thx!

**Comment by longzilicart** [comment]
We use simple rules to fit prompt dimension and feature dimension. This supports images with different resolutions without modifying the prompt dimension. 

Specifically, we use a simple linear interpolation to fit the width and height in each dimension. The prompt channel c can also be different from feature channel C. Obviously, if "c > C", the prompt is wasted and we only use the first C channel. If "c < C", we zero-pad U on the channel to fit C. A simple rule is enough.

**Comment by Note-Liu** [comment]
> We use simple rules to fit prompt dimension and feature dimension. This supports images with different resolutions without modifying the prompt dimension.
> 
> Specifically, we use a simple linear interpolation to fit the width and height in each dimension. The prompt channel c can also be different from feature channel C. Obviously, if "c > C", the prompt is wasted and we only use the first C channel. If "c < C", we zero-pad U on the channel to fit C. A simple rule is enough.

get it!
