### ISSUE TITLE
At least how much graphics memory is needed？

### ISSUE THREAD

**Issue by YangLiu-git** [longzilicart/pip_universal#4]
Hello author, due to my limited computing resources, I do not have the 8 RTX4090 GPUs mentioned in your article. I would like to know if I currently have a 3090 graphics card. By reducing the batch size, can I run your program? Or, at least how much graphics memory is needed? Looking forward to your reply.

**Comment by longzilicart** [comment]
Hi, yes, you can run the program with a single 3090 graphics card. Simply reducing the 'lr' by several times would be fine. For a batch size of 1 with the default patch size, 4-8 GB of graphics memory should be sufficient.

Also, regarding the dataset, if the largest 'image dehazing' dataset isn't necessary for your task, consider removing it or substituting it with your own data. This will save you significant training time.

**Comment by Amazingren** [comment]
> Hi, yes, you can run the program with a single 3090 graphics card. Simply reducing the 'lr' by several times would be fine. For a batch size of 1 with the default patch size, 4-8 GB of graphics memory should be sufficient.
> 
> Also, regarding the dataset, if the largest 'image dehazing' dataset isn't necessary for your task, consider removing it or substituting it with your own data. This will save you significant training time.

HI thanks for this interesting work, may I know how long does it cost to train the proposed method via 8 4090 GPUs?

Best regards and have a nice day,

**Comment by longzilicart** [comment]
> > Hi, yes, you can run the program with a single 3090 graphics card. Simply reducing the 'lr' by several times would be fine. For a batch size of 1 with the default patch size, 4-8 GB of graphics memory should be sufficient.
> > Also, regarding the dataset, if the largest 'image dehazing' dataset isn't necessary for your task, consider removing it or substituting it with your own data. This will save you significant training time.
> 
> HI thanks for this interesting work, may I know how long does it cost to train the proposed method via 8 4090 GPUs?
> 
> Best regards and have a nice day,

Hi, it takes about 30-40 min an epoch for me. :blush:
