### ISSUE TITLE
about feature visualization

### ISSUE THREAD

**Issue by chensming** [longzilicart/pip_universal#5]
Hello, I am very interested in your paper. May I ask how did you visualise this figure?

Do you just take the feature map after the skip connection and do the tsne visualisation, or do you do something to the feature map first (e.g. do the torch.mean operation at [h, w] dimensions)?

![image](https://github.com/longzilicart/pip_universal/assets/45591767/e3f03115-cad6-4689-b978-1ed933ecee22)

**Comment by longzilicart** [comment]
Hi, thank you for your interest. We visualize the generated universal restoration prompt, which serves as the input for the prompt-to-feature interaction. To achieve this, we simply crop or resize the input degraded image to a fixed size, such as 124 or 64, depending on storage cost, thus ensuring the dimensions [h, w] are constant. As our aim is to visualize the prompt itself, no additional processing is required. We just reshaped the prompt to fit the t-SNE input shape, which is done without batching.

Here is the code for convenience:
``` python
prompt_list = [] # same prompt for different dataset
for (dataset_name, dataset) in test_dataset_list:
   fn_center_crop = transforms.CenterCrop(64) # store in memory or disk
   for i, data in enumerate(pbar):
            if i > 300:  #  ensure equal number for each datasets for better visual effect
                break
         # forward 
         .......
         prompt_list.append((net.hook_prompt, de_id)) # get the generated prompt with torch hook
```

Also, this is the processing for t-sne visualization:
```python
extracted_P = np.array([prompt.squeeze(0).reshape(prompt.size(1) * prompt.size(2) * prompt.size(3)).numpy() for prompt, _ in extracted_prompts])
```

**Comment by chensming** [comment]
> Hi, thank you for your interest. We visualize the generated universal restoration prompt, which serves as the input for the prompt-to-feature interaction. To achieve this, we simply crop or resize the input degraded image to a fixed size, such as 124 or 64, depending on storage cost, thus ensuring the dimensions [h, w] are constant. As our aim is to visualize the prompt itself, no additional processing is required. We just reshaped the prompt to fit the t-SNE input shape, which is done without batching.
> 
> Here is the code for convenience:
> 
> ```python
> prompt_list = [] # same prompt for different dataset
> for (dataset_name, dataset) in test_dataset_list:
>    fn_center_crop = transforms.CenterCrop(64) # store in memory or disk
>    for i, data in enumerate(pbar):
>             if i > 300:  #  ensure equal number for each datasets for better visual effect
>                 break
>          # forward 
>          .......
>          prompt_list.append((net.hook_prompt, de_id)) # get the generated prompt with torch hook
> ```
> 
> Also, this is the processing for t-sne visualization:
> 
> ```python
> extracted_P = np.array([prompt.squeeze(0).reshape(prompt.size(1) * prompt.size(2) * prompt.size(3)).numpy() for prompt, _ in extracted_prompts])
> ```

oh, I'd also like to ask what is the size of the np.array fed into t-sne visualization?

From your statement above, the feature dimensions you get at this point should be [number of sample, prompt.size(1) * prompt.size(2) * prompt.size(3)], right?

**Comment by longzilicart** [comment]
> > Hi, thank you for your interest. We visualize the generated universal restoration prompt, which serves as the input for the prompt-to-feature interaction. To achieve this, we simply crop or resize the input degraded image to a fixed size, such as 124 or 64, depending on storage cost, thus ensuring the dimensions [h, w] are constant. As our aim is to visualize the prompt itself, no additional processing is required. We just reshaped the prompt to fit the t-SNE input shape, which is done without batching.
> > Here is the code for convenience:
> > ```python
> > prompt_list = [] # same prompt for different dataset
> > for (dataset_name, dataset) in test_dataset_list:
> >    fn_center_crop = transforms.CenterCrop(64) # store in memory or disk
> >    for i, data in enumerate(pbar):
> >             if i > 300:  #  ensure equal number for each datasets for better visual effect
> >                 break
> >          # forward 
> >          .......
> >          prompt_list.append((net.hook_prompt, de_id)) # get the generated prompt with torch hook
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Also, this is the processing for t-sne visualization:
> > ```python
> > extracted_P = np.array([prompt.squeeze(0).reshape(prompt.size(1) * prompt.size(2) * prompt.size(3)).numpy() for prompt, _ in extracted_prompts])
> > ```
> 
> oh, I'd also like to ask what is the size of the np.array fed into t-sne visualization?
> 
> From your statement above, the feature dimensions you get at this point should be [number of sample, prompt.size(1) * prompt.size(2) * prompt.size(3)], right?

yes

**Comment by chensming** [comment]
> > > Hi, thank you for your interest. We visualize the generated universal restoration prompt, which serves as the input for the prompt-to-feature interaction. To achieve this, we simply crop or resize the input degraded image to a fixed size, such as 124 or 64, depending on storage cost, thus ensuring the dimensions [h, w] are constant. As our aim is to visualize the prompt itself, no additional processing is required. We just reshaped the prompt to fit the t-SNE input shape, which is done without batching.
> > > Here is the code for convenience:
> > > ```python
> > > prompt_list = [] # same prompt for different dataset
> > > for (dataset_name, dataset) in test_dataset_list:
> > >    fn_center_crop = transforms.CenterCrop(64) # store in memory or disk
> > >    for i, data in enumerate(pbar):
> > >             if i > 300:  #  ensure equal number for each datasets for better visual effect
> > >                 break
> > >          # forward 
> > >          .......
> > >          prompt_list.append((net.hook_prompt, de_id)) # get the generated prompt with torch hook
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Also, this is the processing for t-sne visualization:
> > > ```python
> > > extracted_P = np.array([prompt.squeeze(0).reshape(prompt.size(1) * prompt.size(2) * prompt.size(3)).numpy() for prompt, _ in extracted_prompts])
> > > ```
> > 
> > 
> > oh, I'd also like to ask what is the size of the np.array fed into t-sne visualization?
> > From your statement above, the feature dimensions you get at this point should be [number of sample, prompt.size(1) * prompt.size(2) * prompt.size(3)], right?
> 
> yes

And then what is its exact value? I got the number of sample is type of degradation $\times 300$, but what about the second dimension?

**Comment by longzilicart** [comment]
> > > > Hi, thank you for your interest. We visualize the generated universal restoration prompt, which serves as the input for the prompt-to-feature interaction. To achieve this, we simply crop or resize the input degraded image to a fixed size, such as 124 or 64, depending on storage cost, thus ensuring the dimensions [h, w] are constant. As our aim is to visualize the prompt itself, no additional processing is required. We just reshaped the prompt to fit the t-SNE input shape, which is done without batching.
> > > > Here is the code for convenience:
> > > > ```python
> > > > prompt_list = [] # same prompt for different dataset
> > > > for (dataset_name, dataset) in test_dataset_list:
> > > >    fn_center_crop = transforms.CenterCrop(64) # store in memory or disk
> > > >    for i, data in enumerate(pbar):
> > > >             if i > 300:  #  ensure equal number for each datasets for better visual effect
> > > >                 break
> > > >          # forward 
> > > >          .......
> > > >          prompt_list.append((net.hook_prompt, de_id)) # get the generated prompt with torch hook
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Also, this is the processing for t-sne visualization:
> > > > ```python
> > > > extracted_P = np.array([prompt.squeeze(0).reshape(prompt.size(1) * prompt.size(2) * prompt.size(3)).numpy() for prompt, _ in extracted_prompts])
> > > > ```
> > > 
> > > 
> > > oh, I'd also like to ask what is the size of the np.array fed into t-sne visualization?
> > > From your statement above, the feature dimensions you get at this point should be [number of sample, prompt.size(1) * prompt.size(2) * prompt.size(3)], right?
> > 
> > 
> > yes
> 
> And then what is its exact value? I got the number of sample is type of degradation ×300, but what about the second dimension?

The channel size of the universal prompt --- different for each layer and as a hyper-parameter. I set the sample number to no more than 300, which only affects the visual effect since there are datasets with less than 300 samples.

With fixed (c,h,w) as feature size, the t-sne can work well under various sample numbers. And (c,h,w) is also fixed for each layer.

**Comment by chensming** [comment]
> > > > > Hi, thank you for your interest. We visualize the generated universal restoration prompt, which serves as the input for the prompt-to-feature interaction. To achieve this, we simply crop or resize the input degraded image to a fixed size, such as 124 or 64, depending on storage cost, thus ensuring the dimensions [h, w] are constant. As our aim is to visualize the prompt itself, no additional processing is required. We just reshaped the prompt to fit the t-SNE input shape, which is done without batching.
> > > > > Here is the code for convenience:
> > > > > ```python
> > > > > prompt_list = [] # same prompt for different dataset
> > > > > for (dataset_name, dataset) in test_dataset_list:
> > > > >    fn_center_crop = transforms.CenterCrop(64) # store in memory or disk
> > > > >    for i, data in enumerate(pbar):
> > > > >             if i > 300:  #  ensure equal number for each datasets for better visual effect
> > > > >                 break
> > > > >          # forward 
> > > > >          .......
> > > > >          prompt_list.append((net.hook_prompt, de_id)) # get the generated prompt with torch hook
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > Also, this is the processing for t-sne visualization:
> > > > > ```python
> > > > > extracted_P = np.array([prompt.squeeze(0).reshape(prompt.size(1) * prompt.size(2) * prompt.size(3)).numpy() for prompt, _ in extracted_prompts])
> > > > > ```
> > > > 
> > > > 
> > > > oh, I'd also like to ask what is the size of the np.array fed into t-sne visualization?
> > > > From your statement above, the feature dimensions you get at this point should be [number of sample, prompt.size(1) * prompt.size(2) * prompt.size(3)], right?
> > > 
> > > 
> > > yes
> > 
> > 
> > And then what is its exact value? I got the number of sample is type of degradation ×300, but what about the second dimension?
> 
> The channel size of the universal prompt --- different for each layer and as a hyper-parameter. I set the sample number to no more than 300, which only affects the visual effect since there are datasets with less than 300 samples.
> 
> With fixed (c,h,w) as feature size, the t-sne can work well under various sample numbers. And (c,h,w) is also fixed for each layer.

okay, thanks very much. I'll give it a try!

**Comment by progressforever** [comment]
mark it !
