### ISSUE TITLE
t-SNE visualization

### ISSUE THREAD

**Issue by KangLiao929** [longzilicart/pip_universal#7]
Hi Zilong, thanks for your interesting work, Could you please share the complete codes of visualizing the t-SNE map? It would be very helpful for our analysis!

**Comment by longzilicart** [comment]
Hi, here is the procedure: https://github.com/longzilicart/pip_universal/issues/5; and do want the the t-SNE function? For convenience, I just save the generated prompt U to disk and reload and visualize directly.

**Comment by KangLiao929** [comment]
> Hi, here is the procedure: #5; and do want the the t-SNE function? For convenience, I just save the generated prompt U to disk and reload and visualize directly.

Thanks!
